### ISSUE TITLE
Is the path /data/data/com.example.androidcrasher/lib/libcrashpad_handler.so in native-lib.cpp correct?

### ISSUE THREAD

**Issue by ZhaoChunlei** [BugSplat-Git/AndroidCrasher#2]
Is the path /data/data/com.example.androidcrasher/lib/libcrashpad_handler.so in native-lib.cpp correct?
why not native-lib.so in /data/app/.... ?  I am so confused. Tks.

**Comment by bobbyg603** [comment]
@ZhaoChunlei the path is correct as far as we're aware! the device explorer seems to indicate that the path is a symlink:
![image](https://user-images.githubusercontent.com/2646053/90186107-ad884800-dd85-11ea-8ed0-eefe0d00a561.png)

**Comment by bobbyg603** [comment]
@ZhaoChunlei also note this was developed in an Android 11 API 30 emulator so it's possible this file is in a different location on older versions of Android
